[package]
name = "cfg"
version = "0.1.0"
authors = ["mochamad.aditama <mochamad.aditama@mola.tv>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
